milestone 1: authentication
falsefox13/mobileLab pull request #1
Opened 2019-09-21 18:31 UTC by falsefox13

Basic app with Firebase authentication.

2019-09-30 21:12 UTC, nvipash requested changes
First review of Laboratory work #1

General comments:
- **phoneNumber must be saved in Firebase**
- strings should be in strings.xml
- hint parameter should be in XML layouts
- small code formatting moments

Everything else is fine 👌

2019-09-30 21:12 UTC, nvipash commented on app/.gitignore
> +/build
цей .gitigonore можна прибрати

2019-09-30 21:12 UTC, nvipash commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".MainActivity"></activity>
має бути self-closed елемент

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/LoginActivity.java
> +        emailField.setHint("Email");
hint варто вказувати в xml layout

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/LoginActivity.java
> +        alertDialog.setMessage("Please check your email and password");
текст варто тримати в strings.xml та витягувати з нього

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/SignupActivity.java
> +        passField.setHint("Password");
hint варто вказувати в strings.xml

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/SignupActivity.java
> +                .setDisplayName(name).build();
варто ще зберігати номер телефону в instance

2019-09-30 21:12 UTC, nvipash commented on app/src/main/res/layout/signup_activity.xml
> +                android:text="Create Account" />
текст варто зберігати в strings.xml

2019-09-30 21:12 UTC, nvipash commented on app/src/main/res/values/strings.xml
> +    <string name="signup">No account yet? <u><b>Create one</b></u></string>
тут не весь текст

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/SignupActivity.java
> +public class SignupActivity extends AppCompatActivity {
Signup варто записувати як SignUp

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/SignupActivity.java
> +            emailField.setError(null);
а нащо тоді set'ати null як помилку, якщо можна просто не зазначати помилку?

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/LoginActivity.java
> +            return;
варто уникати такого написання if'ів

https://www.oracle.com/technetwork/java/codeconventions-150003.pdf - 7.4

2019-09-30 21:12 UTC, nvipash commented on app/src/main/java/com/example/mobilelab/LoginActivity.java
> +                });
те саме

2019-10-04 19:33 UTC, falsefox13 commented on app/src/main/java/com/example/mobilelab/SignupActivity.java
> +                .setDisplayName(name).build();
Орест дозволив не зберігати, тому що потрібна додаткова верифікація. Решта виправлено.

2019-10-22 17:04 UTC, merged